window.LUT_I18N = {
  zh: {
    home: "首页",
    gallery: "图库",
    menu: "菜单",
    browse: "浏览全部",
    compare: "拖动对比",
    selected: "LUT",
    viewAll: "查看全部 →",
    original: "原片",
    close: "关闭",
    download: "下载 .cube",
    search: "搜索名称或特点",
    count: (n) => `${n} 条 LUT`,
    empty: "没有符合条件的 LUT。",
    footerTag: "胶片模拟与创意 LUT",
    pages: "© 2026 Standard General & mcry416 版权所有",
    galleryTitle: "图库",
    galleryLead: "点开卡片查看特点并下载。",
    heroKicker: "Film & Creative LUTs",
    heroTitle: "LUT",
    heroLead: "富士胶片模拟与创意预设，每条只介绍色彩特点。",
    langLabel: "中文",
    otherLang: "EN",
    notFoundTitle: "没有这一页",
    notFoundLead: "链接可能写错了。",
    backHome: "回到首页",
    toGallery: "去图库",
  },
  en: {
    home: "Home",
    gallery: "Gallery",
    menu: "Menu",
    browse: "Browse all",
    compare: "Drag to compare",
    selected: "LUTs",
    viewAll: "View all →",
    original: "Original",
    close: "Close",
    download: "Download .cube",
    search: "Search name or look",
    count: (n) => `${n} LUTs`,
    empty: "No matching LUTs.",
    footerTag: "Film and creative LUTs",
    pages: "© 2026 Standard General & mcry416. All rights reserved.",
    galleryTitle: "Gallery",
    galleryLead: "Open a card to read the look and download.",
    heroKicker: "Film & Creative LUTs",
    heroTitle: "LUTs",
    heroLead: "Fujifilm simulations and creative looks. Each LUT is introduced by its color only.",
    langLabel: "EN",
    otherLang: "中文",
    notFoundTitle: "Page not found",
    notFoundLead: "This link may be wrong.",
    backHome: "Back home",
    toGallery: "Gallery",
  },
};

window.LUT_CATEGORIES = [
  { id: "all", zh: "全部", en: "All" },
  { id: "reversal", zh: "反转", en: "Reversal" },
  { id: "negative", zh: "负片", en: "Negative" },
  { id: "cinema", zh: "电影", en: "Cinema" },
  { id: "creative", zh: "创意", en: "Creative" },
];

window.LUT_CATALOG = [
  {
    id: "astia",
    nameZh: "雅诗 ASTIA",
    nameEn: "ASTIA Soft",
    category: "reversal",
    tagsZh: ["柔和", "人像"],
    tagsEn: ["Soft", "Portrait"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/ASTIA.cube",
    preview: "assets/ref_girl_spanish.jpeg",
    palette: ["#2a3340", "#6a7a88", "#c4a090", "#e8d4c0", "#4a6a70"],
    summaryZh: "反差柔和，肤色自然，饱和克制，适合人像和日常。",
    summaryEn: "Soft contrast, natural skin, restrained saturation — portraits and everyday scenes.",
  },
  {
    id: "provia",
    nameZh: "普罗维亚 PROVIA",
    nameEn: "PROVIA Standard",
    category: "reversal",
    tagsZh: ["标准", "中性"],
    tagsEn: ["Standard", "Neutral"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/PROVIA.cube",
    preview: "assets/ref_city_japan_2.jpg",
    palette: ["#1c2430", "#4a5a68", "#c8a070", "#e8e0d4", "#3a5080"],
    summaryZh: "色彩接近所见，层次均衡，干净中性。",
    summaryEn: "True-to-eye color, even tonality, clean and neutral.",
  },
  {
    id: "velvia",
    nameZh: "威达 Velvia",
    nameEn: "Velvia Vivid",
    category: "reversal",
    tagsZh: ["浓郁", "风景"],
    tagsEn: ["Vivid", "Landscape"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/Velvia.cube",
    preview: "assets/ref_scene_1.jpg",
    palette: ["#0c1830", "#1a4a80", "#e87820", "#f0d060", "#1a6a40"],
    summaryZh: "高饱和、高反差，绿和蓝被推得很满，风景更跳。",
    summaryEn: "High saturation and contrast; greens and blues packed for landscapes.",
  },
  {
    id: "reala-ace",
    nameZh: "真实 ACE",
    nameEn: "REALA ACE",
    category: "negative",
    tagsZh: ["自然", "略暖"],
    tagsEn: ["Natural", "Warm"],
    featured: false,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/REALA-ACE.cube",
    preview: "assets/ref_scene_park_1.jpg",
    palette: ["#2a241c", "#6a5848", "#d4a878", "#eee4d4", "#4a6870"],
    summaryZh: "层次细、颜色稳，略暖，接近经典负片的自然感。",
    summaryEn: "Fine gradation, stable color, slightly warm — a classic negative naturalness.",
  },
  {
    id: "pro-neg",
    nameZh: "专业负片",
    nameEn: "PRO Neg.",
    category: "negative",
    tagsZh: ["低反差", "肤色"],
    tagsEn: ["Flat", "Skin"],
    featured: false,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/PRO_Neg.cube",
    preview: "assets/ref_city_japan_4.jpg",
    palette: ["#3a3a38", "#7a7870", "#c0b8a8", "#e8e4dc", "#5a6870"],
    summaryZh: "反差低、容度宽，肤色平滑，适合后级再调。",
    summaryEn: "Low contrast, wide latitude, smooth skin — a starting point for further grading.",
  },
  {
    id: "classic-chrome",
    nameZh: "经典正片",
    nameEn: "Classic Chrome",
    category: "negative",
    tagsZh: ["纪录", "克制"],
    tagsEn: ["Documentary", "Muted"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/CC.cube",
    preview: "assets/ref_city_japan_5.jpg",
    palette: ["#2c3034", "#5a6068", "#b8a090", "#d8d0c4", "#6a7880"],
    summaryZh: "饱和压低，略硬，有纪录和杂志印刷的味道。",
    summaryEn: "Lower saturation, a harder edge — documentary and print-magazine character.",
  },
  {
    id: "classic-negative",
    nameZh: "经典负片",
    nameEn: "Classic Negative",
    category: "negative",
    tagsZh: ["当代", "胶片"],
    tagsEn: ["Contemporary", "Film"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/CN.cube",
    preview: "assets/ref_city_japan_3.jpg",
    palette: ["#343830", "#6a7058", "#c4b080", "#e4dcc8", "#5a6870"],
    summaryZh: "色彩稍褪，阴影带一点绿黄，当代胶片感。",
    summaryEn: "Slightly faded color, green-yellow shadows — a contemporary film look.",
  },
  {
    id: "eterna",
    nameZh: "ETERNA",
    nameEn: "ETERNA",
    category: "cinema",
    tagsZh: ["电影", "低反差"],
    tagsEn: ["Cinema", "Low contrast"],
    featured: true,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/ETERNA.cube",
    preview: "assets/ref_wallpaper_scene.jpg",
    palette: ["#2a2e30", "#5a6468", "#b8a898", "#d8d4cc", "#4a5a60"],
    summaryZh: "低反差、色彩收敛，中间调软，电影长镜头常用。",
    summaryEn: "Low contrast, held-back color, soft mids — a motion-picture work look.",
  },
  {
    id: "eterna-bb",
    nameZh: "ETERNA 漂白",
    nameEn: "ETERNA Bleach Bypass",
    category: "cinema",
    tagsZh: ["漂白", "银影"],
    tagsEn: ["Bleach", "Silver"],
    featured: false,
    size: "65×65×65",
    input: "Rec.709",
    file: "assets/luts/ETERNA-BB.cube",
    preview: "assets/ref_city_japan_1.jpg",
    palette: ["#1c1e20", "#4a4e52", "#8a8e90", "#d0d0cc", "#6a6e70"],
    summaryZh: "在 Eterna 上再压饱和、提银影，冷硬、金属感。",
    summaryEn: "Eterna pushed toward silver: less color, more density, a cold metallic edge.",
  },
  {
    id: "palm-springs",
    nameZh: "棕榈泉 Palm Springs",
    nameEn: "Presetpro Palm Springs",
    category: "creative",
    tagsZh: ["夏日", "生机"],
    tagsEn: ["Summer", "Vivid"],
    featured: true,
    size: "64×64×64",
    input: "Rec.709",
    file: "assets/luts/Presetpro-Palm Springs.cube",
    preview: "assets/ref_palm_town.jpg",
    palette: ["#1a2830", "#c87828", "#e8c040", "#f0e0b8", "#2a6a58"],
    summaryZh: "夏日炎炎，色彩饱满而有生机，热浪与阳光感。",
    summaryEn: "Blazing summer color — vivid, sun-soaked, and full of life.",
  },
  {
    id: "lomography",
    nameZh: "洛莫 Lomography",
    nameEn: "Presetpro Lomography",
    category: "creative",
    tagsZh: ["昏光", "层次"],
    tagsEn: ["Low light", "Depth"],
    featured: true,
    size: "32×32×32",
    input: "Rec.709",
    file: "assets/luts/Presetpro-Lomography.cube",
    preview: "assets/ref_korea_street.jpg",
    palette: ["#121018", "#3a2848", "#8a3a50", "#c89060", "#2a4058"],
    summaryZh: "昏光下把暗部颜色拆得更开，层次更深、更有胶片感。",
    summaryEn: "In dim light, deeper colors unfold from the shadows.",
  },
  {
    id: "agfa-lebox",
    nameZh: "爱克发 LeBox",
    nameEn: "AgfaPhoto LeBox",
    category: "negative",
    tagsZh: ["偏冷", "胶片"],
    tagsEn: ["Cool", "Film"],
    featured: true,
    size: "33×33×33",
    input: "Rec.709",
    file: "assets/luts/VOL 23 TXD AgfaPhoto LeBox.cube",
    preview: "assets/ref_city_nanjing_1.jpg",
    palette: ["#1c2838", "#4a6878", "#8aa8b0", "#d4dce0", "#3a5868"],
    summaryZh: "整体偏冷，高光和阴影带一点青蓝，轻胶片感。",
    summaryEn: "A cool film look, with a cyan-blue cast in highlights and shadows.",
  },
  {
    id: "snow-portrait",
    nameZh: "雪景人像",
    nameEn: "Snow Portrait",
    category: "creative",
    tagsZh: ["人像", "清冷"],
    tagsEn: ["Portrait", "Cool"],
    featured: true,
    size: "33×33×33",
    input: "Rec.709",
    file: "assets/luts/snow_portrait.cube",
    preview: "assets/ref_girl_spanish.jpeg",
    palette: ["#2a3038", "#6a7888", "#c8b0a0", "#e8e4e0", "#5a7080"],
    summaryZh: "清冷底色，肤色透亮，适合冷调背景的人像。",
    summaryEn: "Cool, clear skin against a cold backdrop — made for cool-toned portraits.",
  },
  {
    id: "rice-paddy",
    nameZh: "稻田 Rice Paddy",
    nameEn: "Rice Paddy Film",
    category: "creative",
    tagsZh: ["田野", "绿黄"],
    tagsEn: ["Fields", "Green"],
    featured: true,
    size: "33×33×33",
    input: "Rec.709",
    file: "assets/luts/RicePaddyFilm.cube",
    preview: "assets/ref_scene_park_2.jpg",
    palette: ["#2a3020", "#6a7840", "#c4b060", "#dce8c8", "#4a6848"],
    summaryZh: "田野风光里，绿和黄过渡更顺，层次协调。",
    summaryEn: "Field landscapes with smoother green-to-yellow transitions.",
  },
];
